---
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.2
    hooks:
      - id: check-jsonschema
        name: Validating index file
        args:
          - --schemafile
          - schema.json
        files: index.yaml$
